# Generated by Django 5.1 on 2024-08-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identificationNumber',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
